typography_spectrum: 0.11012983624823391
color:
  brandStrength: 0.5394142377190292
  lightness: 0.6548392528202385
  saturation: 0.7501101712696254
  rhythmicContrast: 0.6059616385027766
  brandColors:
    - '#FF5335'
    - '#B39C85'
    - '#306E73'
    - '#3B424D'
    - '#1D181F'
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/1029a066-6d99-4193-82f0-94001d37c011.jpg
layout_spectrum: 0.0998975420370698
analytics:
  facebook: '1606499059648421'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7c1b1683-a82f-4185-9417-2280f817c65e.jpg
name: Hermsen Visuals
navigation:
  - name: About Us
    id: 1d4d1f32-192d-4824-8c17-17c4e2f29be5
    type: content
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Hermsen Visuals
description: Redefining Media
