title: Hermsen Visuals
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/1029a066-6d99-4193-82f0-94001d37c011.jpg
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7c1b1683-a82f-4185-9417-2280f817c65e.jpg
description: Redefining Media
color:
  saturation: 0.1840106903109699
  brandStrength: 0.6778428496327251
  lightness: 0.7003439059481025
  brandColors:
    - '#FFFFFF'
    - '#ED351D'
    - '#1CABED'
    - '#21ED1C'
    - '#1D26ED'
  rhythmicContrast: 0.816124907694757
typography_spectrum: 0.6278195
navigation:
  - name: About Us
    id: 1d4d1f32-192d-4824-8c17-17c4e2f29be5
    type: content
layout_spectrum: 1
name: Hermsen Visuals
