layout_spectrum: 0.8048024266026914
typography_spectrum: 0.47480104863643646
color:
  brandStrength: 0.7298318475950509
  lightness: 0.9273212505504489
  saturation: 0.5483104190789163
  rhythmicContrast: 0.2722689462825656
  brandColors:
    - '#595241'
    - '#B8AE9C'
    - '#FFFFFF'
    - '#ACCFCC'
    - '#8A0917'
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/1029a066-6d99-4193-82f0-94001d37c011.jpg
analytics:
  facebook: '996555217122614'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7c1b1683-a82f-4185-9417-2280f817c65e.jpg
name: Hermsen Visuals
navigation:
  - name: About Us
    id: 1d4d1f32-192d-4824-8c17-17c4e2f29be5
    type: content
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Hermsen Visuals
description: Redefining Media
