title: Hermsen Visuals
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/1029a066-6d99-4193-82f0-94001d37c011.jpg
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7c1b1683-a82f-4185-9417-2280f817c65e.jpg
description: Redefining Media
color:
  brandStrength: 0.8224076447077096
  lightness: 0.9617300238460302
  saturation: 0.9602852156385779
  rhythmicContrast: 0.1377216838300228
  brandColors:
    - '#DC3522'
    - '#D9CB9E'
    - '#374140'
    - '#2A2C2B'
    - '#1E1E20'
typography_spectrum: 0.6917535529937595
navigation:
  - name: About Us
    id: 1d4d1f32-192d-4824-8c17-17c4e2f29be5
    type: content
layout_spectrum: 0.30281832232140005
name: Hermsen Visuals
