title: Hermsen Visuals
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/1029a066-6d99-4193-82f0-94001d37c011.jpg
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7c1b1683-a82f-4185-9417-2280f817c65e.jpg
description: Redefining Media
color:
  brandStrength: 0.9178801567759365
  lightness: 0.416328439489007
  saturation: 0.5165584334172308
  rhythmicContrast: 0.6153583389241248
  brandColors:
    - '#E7E8D1'
    - '#D3CEAA'
    - '#FBF7E4'
    - '#424242'
    - '#8E001C'
typography_spectrum: 0.3288322570733726
navigation:
  - name: About Us
    id: 1d4d1f32-192d-4824-8c17-17c4e2f29be5
    type: content
layout_spectrum: 0.6135537684895098
name: Hermsen Visuals
